[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

log_cli = false

addopts = -v --alluredir=reports/allure-results --reruns 2 --reruns-delay 2

markers =
    smoke: critical test cases
    regression: full regression suite
    ui: UI automation tests
    api: API automation tests
    e2e: hybrid end-to-end tests
    negative: negative test cases